name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  HELM_EXPERIMENTAL_OCI: 1

jobs:

  build_push_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bcglabacr01.azurecr.io/courseassessment:gharasim01
    
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: bcglabacr01
        # Container registry password
        password: ${{ secrets.ACR_CREDENTIALS }} 
        # Container registry server url
        login-server: bcglabacr01.azurecr.io
        
    - name: Push Image  
      run: docker push bcglabacr01.azurecr.io/courseassessment:gharasim01

    - name: Helm tool installer
      uses: Azure/setup-helm@v1
      with:
        # Version of helm
        version: 3.3.1

    - name: Login to ACR using HELM
      run: |
        echo $ | helm registry login bcglabacr01.azurecr.io --username bcglabacr01 --password vQign8/X5HO3XhfXFWFW05CtHqpYV+dM
    - name: Package the helm chart
      run: helm package ./helm/charts-courseassessment-gracjan-api

    - name: save helm chart to local registry
      run: |
       helm chart save ./charts-courseassessment-gracjan-api-0.1.0.tgz barclaysacr02.azurecr.io/charts-courseassessment-gracjan-api:v02
    - name: Helm chart Push
      run: helm chart push bcglabacr01.azurecr.io/charts-courseassessment-gracjan-api:v02

  deploy:
    runs-on: ubuntu-latest
    needs: build_push_image # Will wait for the execution of the previous job 

    steps:
    - uses: actions/checkout@v2

    - name: Kubernetes set context
      uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{secrets.KUBECONFIG}} # Grab the auth token from GitHub secrets
      id: login
